#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [adm, sudo]
    shell: /bin/bash
    ssh_authorized_keys:
      # Private aws key mert1
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxzqd8EpxDmz0NPxozSSw5ndHiMfHE+3LpVgmK197oWHArexunNFzxox6EB0RVDwH6Fx9bppfTCkdl49NSHF+IojyC2MN+H+llsiKZWI82f8jGjUsx2nzprP+MAgdgcMmDEBtTowa6fxNIm1jHofLAuKrxA1+wjM90laZfHxoVzf51PdUfN9jyiqYho4MomJGwWZtd4NX55aVkpBuCM0TEA9HhXNfTHC/cHsXNSpVZ3nQQ3xcaW2sjhkF0re9PPQUFE2bBZItruFfqpZt6VUoid+8V98Ri9wP1zzW3wXxyRsH1imTGm73Kul9DN6speI3rXArXXVZno+t/gD6mepoR mert-key

      # SSH-Key Lerhperson
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpYQGN6ZsQ+5UJzDz05HogRp0sTBfaore2SjtIpyIc0hyHRQMjw6zeG7+BHglRej/2nXKkRVvXfAzzYQoNxvh38ZcXaqp600UQ1T8zmlU700jvSBew9/UxyvGC9w0iClq/73tMX7k38dUEJTrNVhatHlZYdjbDxKp6mwIFiFpDQnyz3FKfc26gl+wF5DFCcIiRQyIS7iG5G+3drBWwt7FNYxAgcUHZCCx9cyOJw8VqOB0JxvztBXbOS2PJINAaa4jpGIP4n+iLhGY0q87fizLFEz9A8MX3hQVqLXOH1XDtQybv+J4qOOYSAr58ASEkpYxZyJyRxnPfXJyCPs0keIvlkn02 keypair1
  
ssh_pwauth: false
disable_root: true

packages:
  - mariadb-server

runcmd:
  - sudo systemctl enable mariadb
  - sudo systemctl start mariadb
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'm346_1234' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf || true
  - sudo systemctl restart mariadb
  - sudo systemctl status mariadb --no-pager
